# schemas.py is a curated version of schemas-codegen.py which is a file that was
# generated using datamodel-code-generator that creates pydantic models from just about any data source. 
# In this case, the data source was psconfig-schema.json that can be found here - 
# https://github.com/perfsonar/psconfig/blob/master/psconfig/perfsonar-psconfig/doc/psconfig-schema.json
# This was the command that was used 
# datamodel-codegen  --input psconfig-schema.json --input-file-type jsonschema --output schemas-codegen.py

# generated by datamodel-codegen:
#   filename:  psconfig-schema.json
#   timestamp: 2025-01-16T20:52:55+00:00

from __future__ import annotations

from enum import Enum
from ipaddress import IPv4Address, IPv6Address
from typing import Any, Dict, List, Optional, Union
from datetime import datetime
from pydantic import AnyUrl, BaseModel, Extra, Field, conint, constr

# Custom JSON type
class AnyJSON(BaseModel):
    __root__: Optional[Union[List, bool, int, float, Dict[str, Any], str]]


# Base types
class Cardinal(BaseModel):
    __root__: conint(ge=1)


class Duration(BaseModel):
    __root__: constr(
        regex=r'^P(?:\d+(?:\.\d+)?W)?(?:\d+(?:\.\d+)?D)?(?:T(?:\d+(?:\.\d+)?H)?(?:\d+(?:\.\d+)?M)?(?:\d+(?:\.\d+)?S)?)?$'
    )


class IntegerZero(BaseModel):
    __root__: conint(ge=0)


class NameType(BaseModel):
    __root__: constr(regex=r'^[a-zA-Z0-9:._\-]+$')


class HostName(BaseModel):
    __root__: constr(
        regex=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])\Z'
    )


class HostNamePort(BaseModel):
    __root__: constr(
        regex=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])(:[0-9]+)?$'
    )


class IPAddress(BaseModel):
    __root__: Union[IPv4Address, IPv6Address]


class IPv6RFC2732(BaseModel):
    __root__: constr(
        regex=r'^\[(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\](:[0-9]+)?$'
    )


class Timestamp(BaseModel):
    __root__: constr(
        regex=r'^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$'
    )


class Host(BaseModel):
    __root__: Union[HostName, IPAddress]


class TimestampAbsoluteRelative(BaseModel):
    __root__: Union[
        Timestamp,
        Duration,
        constr(
            regex=r'^@(R\d*/)?P(?:\d+(?:\.\d+)?Y)?(?:\d+(?:\.\d+)?M)?(?:\d+(?:\.\d+)?W)?(?:\d+(?:\.\d+)?D)?(?:T(?:\d+(?:\.\d+)?H)?(?:\d+(?:\.\d+)?M)?(?:\d+(?:\.\d+)?S)?)?$'
        ),
    ]


class URLHostPort(BaseModel):
    __root__: Union[HostNamePort, IPv6RFC2732]


# Selectors
class AddressSelectorClass(BaseModel):
    class Config:
        extra = Extra.forbid

    class_: NameType = Field(..., alias='class')
    disabled: Optional[bool] = None


class AddressSelectorNameLabel(BaseModel):
    class Config:
        extra = Extra.forbid

    name: NameType
    label: Optional[NameType] = None
    disabled: Optional[bool] = None


class AddressSelector(BaseModel):
    __root__: Union[AddressSelectorClass, AddressSelectorNameLabel]


# Enum categories
class GroupType(Enum):
    DISJOINT = 'disjoint'
    LIST = 'list'
    MESH = 'mesh'

class ExcludesSelfScope(Enum):
    HOST = 'host'
    ADDRESS = 'address'
    DISABLED = 'disabled'


# Core Models
class ArchiveJQTransformSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    script: Union[str, List[str]]
    output_raw: Optional[bool] = Field(None, alias='output-raw')
    args: Optional[AnyJSON] = None


class ArchiveSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    archiver: str
    data: AnyJSON
    transform: Optional[ArchiveJQTransformSpecification] = None
    ttl: Optional[Duration] = None
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')
    label: Optional[str] = None
    schema_: Optional[Cardinal] = Field(None, alias='schema')


class ContextSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    context: str
    data: AnyJSON
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class TaskSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    scheduled_by: Optional[IntegerZero] = Field(None, alias='scheduled-by')
    group: NameType
    test: NameType
    schedule: Optional[NameType] = None
    disabled: Optional[bool] = None
    archives: Optional[List[NameType]] = None
    tools: Optional[List[str]] = None
    subtasks: Optional[List[NameType]] = None
    priority: Optional[int] = None
    reference: Optional[AnyJSON] = None
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class TestSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    type: str
    spec: AnyJSON
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class ScheduleSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    start: Optional[TimestampAbsoluteRelative] = None
    slip: Optional[Duration] = None
    sliprand: Optional[bool] = None
    repeat: Optional[Duration] = None
    until: Optional[TimestampAbsoluteRelative] = None
    max_runs: Optional[Cardinal] = Field(None, alias='max-runs')
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class HostSpecificationLabelMapItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: Host
    lead_bind_address: Optional[Host] = Field(None, alias='lead-bind-address')
    pscheduler_address: Optional[URLHostPort] = Field(None, alias='pscheduler-address')
    contexts: Optional[List[NameType]] = None
    disabled: Optional[bool] = None
    no_agent: Optional[bool] = Field(None, alias='no-agent')
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class HostSpecificationLabelMap(BaseModel):
    class Config:
        extra = Extra.forbid

    __root__: Dict[
        constr(regex=r'^[a-zA-Z0-9:._\-]+$'), HostSpecificationLabelMapItem
    ]


class HostSpecificationRemoteMapItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: Optional[Host] = None
    labels: Optional[HostSpecificationLabelMap] = None
    lead_bind_address: Optional[Host] = Field(None, alias='lead-bind-address')
    pscheduler_address: Optional[URLHostPort] = Field(None, alias='pscheduler-address')
    contexts: Optional[List[NameType]] = None
    disabled: Optional[bool] = None
    no_agent: Optional[bool] = Field(None, alias='no-agent')
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class HostSpecificationRemoteMap(BaseModel):
    class Config:
        extra = Extra.forbid

    __root__: Dict[
        constr(regex=r'^[a-zA-Z0-9:._\-]+$'), HostSpecificationRemoteMapItem
    ]


class HostSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    address: Host
    host: Optional[NameType] = None
    labels: Optional[HostSpecificationLabelMap] = None
    remote_addresses: Optional[HostSpecificationRemoteMap] = Field(
        None, alias='remote-addresses'
    )
    lead_bind_address: Optional[Host] = Field(None, alias='lead-bind-address')
    pscheduler_address: Optional[URLHostPort] = Field(None, alias='pscheduler-address')
    contexts: Optional[List[NameType]] = None
    tags: Optional[List[str]] = None
    disabled: Optional[bool] = None
    no_agent: Optional[bool] = Field(None, alias='no-agent')
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class ExcludesAddressPair(BaseModel):
    class Config:
        extra = Extra.forbid

    local_address: AddressSelector = Field(..., alias='local-address')
    target_addresses: List[AddressSelector] = Field(..., alias='target-addresses')


class ExcludesAddressPairList(BaseModel):
    __root__: List[ExcludesAddressPair]


class GroupListSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    default_address_label: Optional[str] = Field(None, alias='default-address-label')
    type: GroupType
    addresses: List[AddressSelector]
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class GroupDisjointSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    default_address_label: Optional[str] = Field(None, alias='default-address-label')
    unidirectional: Optional[bool] = None
    type: GroupType
    a_addresses: List[AddressSelector] = Field(..., alias='a-addresses')
    b_addresses: List[AddressSelector] = Field(..., alias='b-addresses')
    excludes_self: Optional[ExcludesSelfScope] = Field(None, alias='excludes-self')
    excludes: Optional[ExcludesAddressPairList] = None
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class GroupMeshSpecification(BaseModel):
    class Config:
        extra = Extra.forbid

    default_address_label: Optional[str] = Field(None, alias='default-address-label')
    type: GroupType
    addresses: List[AddressSelector]
    excludes_self: Optional[ExcludesSelfScope] = Field(None, alias='excludes-self')
    excludes: Optional[ExcludesAddressPairList] = None
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class GroupSpecification(BaseModel):
    __root__: Union[
        GroupDisjointSpecification, GroupListSpecification, GroupMeshSpecification
    ]


class pSConfigSchema(BaseModel):
    class Config:
        extra = Extra.forbid

    archives: Optional[
        Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), ArchiveSpecification]
    ] = None
    contexts: Optional[
        Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), ContextSpecification]
    ] = None
    groups: Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), GroupSpecification]
    hosts: Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), HostSpecification]
    includes: Optional[List[AnyUrl]] = None
    schedules: Optional[
        Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), ScheduleSpecification]
    ] = None
    tasks: Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), TaskSpecification]
    tests: Dict[constr(regex=r'^[a-zA-Z0-9:._\-]+$'), TestSpecification]
    field_meta: Optional[AnyJSON] = Field(None, alias='_meta')


class DataTableBase(BaseModel):
    ref_set: Optional[List[str]]
    type: str
    # json: Union[Dict[str, Archives], Dict[str, Hosts], Dict[str, Groups], Dict[str, Schedules], Dict[str, Meta], Dict[str, Tasks], Dict[str, Tests], Templates]
    # TODO : Check this below? The json can be a subtype as well, eg : if we're storing just an archive, then we won't have the entire schema object
    json_field: pSConfigSchema = Field(None, alias="json")
    name: str
    created_by: str
    created_at: datetime
    last_edited_by: str
    last_edited_at: datetime
    url: str


pSConfigSchema.update_forward_refs()
