/** @type {import('tailwindcss').Config} */
import * as tokens from "@esnet/esnet-tokens";

module.exports = {
  content: ["./mockups/**/*.html"],
  theme: {
    fontFamily: {
      sans: ["Source Sans 3", "Open Sans", "sans-serif"],
      mono: ["Source Code Pro", "monospace"],
      display: ["Signika", "Open Sans", "sans-serif"],
    },
    colors: {
      black: {
        100: tokens.ESNET_COLOR_CORE_BLACK_100,
        200: tokens.ESNET_COLOR_CORE_BLACK_200,
        300: tokens.ESNET_COLOR_CORE_BLACK_300,
        400: tokens.ESNET_COLOR_CORE_BLACK_400,
        500: tokens.ESNET_COLOR_CORE_BLACK_500,
        600: tokens.ESNET_COLOR_CORE_BLACK_600,
        700: tokens.ESNET_COLOR_CORE_BLACK_700,
        800: tokens.ESNET_COLOR_CORE_BLACK_800,
        900: tokens.ESNET_COLOR_CORE_BLACK_900,
        1000: tokens.ESNET_COLOR_CORE_BLACK_1000,
      },
      white: {
        100: tokens.ESNET_COLOR_CORE_WHITE_100,
        200: tokens.ESNET_COLOR_CORE_WHITE_200,
        300: tokens.ESNET_COLOR_CORE_WHITE_300,
        400: tokens.ESNET_COLOR_CORE_WHITE_400,
        500: tokens.ESNET_COLOR_CORE_WHITE_500,
        600: tokens.ESNET_COLOR_CORE_WHITE_600,
        700: tokens.ESNET_COLOR_CORE_WHITE_700,
        800: tokens.ESNET_COLOR_CORE_WHITE_800,
        900: tokens.ESNET_COLOR_CORE_WHITE_900,
        1000: tokens.ESNET_COLOR_CORE_WHITE_1000,
      },
      slate: {
        50: tokens.ESNET_COLOR_CORE_WHITE_50,
        100: tokens.ESNET_COLOR_CORE_WHITE_100,
        200: tokens.ESNET_COLOR_CORE_WHITE_200,
        300: tokens.ESNET_COLOR_CORE_WHITE_300,
        400: tokens.ESNET_COLOR_CORE_WHITE_400,
        500: tokens.ESNET_COLOR_CORE_WHITE_500,
        600: tokens.ESNET_COLOR_CORE_WHITE_600,
        700: tokens.ESNET_COLOR_CORE_WHITE_700,
        800: tokens.ESNET_COLOR_CORE_WHITE_800,
        900: tokens.ESNET_COLOR_CORE_WHITE_900,
        1000: tokens.ESNET_COLOR_CORE_WHITE_1000,
      },
      blue: {
        100: tokens.ESNET_COLOR_CORE_BLUE_100,
        200: tokens.ESNET_COLOR_CORE_BLUE_200,
        300: tokens.ESNET_COLOR_CORE_BLUE_300,
        400: tokens.ESNET_COLOR_CORE_BLUE_400,
        500: tokens.ESNET_COLOR_CORE_BLUE_500,
        600: tokens.ESNET_COLOR_CORE_BLUE_600,
        700: tokens.ESNET_COLOR_CORE_BLUE_700,
        800: tokens.ESNET_COLOR_CORE_BLUE_800,
        900: tokens.ESNET_COLOR_CORE_BLUE_900,
        1000: tokens.ESNET_COLOR_CORE_BLUE_1000,
      },     
      red: {
        100: tokens.ESNET_COLOR_CORE_RED_100,
        200: tokens.ESNET_COLOR_CORE_RED_200,
        300: tokens.ESNET_COLOR_CORE_RED_300,
        400: tokens.ESNET_COLOR_CORE_RED_400,
        500: tokens.ESNET_COLOR_CORE_RED_500,
        600: tokens.ESNET_COLOR_CORE_RED_600,
        700: tokens.ESNET_COLOR_CORE_RED_700,
        800: tokens.ESNET_COLOR_CORE_RED_800,
        900: tokens.ESNET_COLOR_CORE_RED_900,
        1000: tokens.ESNET_COLOR_CORE_RED_1000,
      },
    },
    extend: {
      colors: {
        primary: {
          primary: tokens.ESNET_COLOR_LIGHT_PRIMARY,
          secondary: tokens.ESNET_COLOR_LIGHT_SECONDARY,
          accent: tokens.ESNET_COLOR_LIGHT_ACCENT,
          background: tokens.ESNET_COLOR_LIGHT_BACKGROUND,
      "surface_1": tokens.ESNET_COLOR_LIGHT_SURFACE_1,
      "surface_2": tokens.ESNET_COLOR_LIGHT_SURFACE_2,
          shadow: tokens.ESNET_COLOR_LIGHT_SHADOW,
          copy: tokens.ESNET_COLOR_LIGHT_COPY,
          copyAlt: tokens.ESNET_COLOR_LIGHT_COPY_ALT,
      "copyAlt_2": tokens.ESNET_COLOR_LIGHT_COPY_ALT_2,
          success: tokens.ESNET_COLOR_LIGHT_SUCCESS,
          warning: tokens.ESNET_COLOR_LIGHT_WARNING,
          error: tokens.ESNET_COLOR_LIGHT_ERROR,
        },
        dark: {
          primary: tokens.ESNET_COLOR_DARK_PRIMARY,
          secondary: tokens.ESNET_COLOR_DARK_SECONDARY,
          accent: tokens.ESNET_COLOR_DARK_ACCENT,
          background: tokens.ESNET_COLOR_DARK_BACKGROUND,
      "surface_1": tokens.ESNET_COLOR_DARK_SURFACE_1,
      "surface_2": tokens.ESNET_COLOR_DARK_SURFACE_2,
          shadow: tokens.ESNET_COLOR_DARK_SHADOW,
          copy: tokens.ESNET_COLOR_DARK_COPY,
          copyAlt: tokens.ESNET_COLOR_DARK_COPY_ALT,
      "copyAlt_2": tokens.ESNET_COLOR_DARK_COPY_ALT_2,
          success: tokens.ESNET_COLOR_DARK_SUCCESS,
          warning: tokens.ESNET_COLOR_DARK_WARNING,
          error: tokens.ESNET_COLOR_DARK_ERROR,
        },
        surface: {
          1: tokens.ESNET_COLOR_DARK_SURFACE_1,
          2: tokens.ESNET_COLOR_DARK_SURFACE_2,
          bg: tokens.ESNET_COLOR_DARK_BACKGROUND,
        },
      },
    },
  },
  plugins: [],
};

