# Serve pSCompose frontend static files
Alias /pscompose /usr/lib/perfsonar/pscompose/frontend

<Directory /usr/lib/perfsonar/pscompose/frontend>
    SSLRequireSSL
    Options -Indexes
    AllowOverride None
    Require all granted
</Directory>

# Reverse proxy /pscompose/api to the pSCompose Gunicorn/Uvicorn service
<Location /pscompose/api>
    SSLRequireSSL

    ProxyPreserveHost On
    ProxyPass unix:/run/perfsonar/pscompose.sock|http://localhost/pscompose/api
    ProxyPassReverse unix:/run/perfsonar/pscompose.sock|http://localhost/pscompose/api

    Require all granted
</Location>